/*
 * Copyright 2013 Harald Postner <Harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.jury;

/**
 *
 * @author Harald Postner <Harald at free-creations.de>
 */
public class TimeTableCellPanel extends javax.swing.JPanel {

  /**
   * Creates new form TimeTableCellPanel
   */
  public TimeTableCellPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblLocation = new javax.swing.JLabel();
    btnCheck = new javax.swing.JCheckBox();
    lblTime = new javax.swing.JTextField();

    setBackground(new java.awt.Color(255, 255, 255));

    lblLocation.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    lblLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/free_creations/editors/resources/house.png"))); // NOI18N
    org.openide.awt.Mnemonics.setLocalizedText(lblLocation, org.openide.util.NbBundle.getMessage(TimeTableCellPanel.class, "TimeTableCellPanel.lblLocation.text")); // NOI18N

    btnCheck.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    btnCheck.setSelected(true);
    org.openide.awt.Mnemonics.setLocalizedText(btnCheck, org.openide.util.NbBundle.getMessage(TimeTableCellPanel.class, "TimeTableCellPanel.btnCheck.text")); // NOI18N
    btnCheck.setOpaque(false);
    btnCheck.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCheckActionPerformed(evt);
      }
    });

    lblTime.setText(org.openide.util.NbBundle.getMessage(TimeTableCellPanel.class, "TimeTableCellPanel.lblTime.text")); // NOI18N
    lblTime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(btnCheck)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblTime))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(lblLocation)
        .addGap(0, 0, 0)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lblTime)
          .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
    // TODO add your handling code here:
    if (btnCheck.isSelected()) {
      lblLocation.setEnabled(true);
      lblTime.setEnabled(true);
    } else {
      lblLocation.setEnabled(false);
      lblTime.setEnabled(false);
    }
  }//GEN-LAST:event_btnCheckActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox btnCheck;
  private javax.swing.JLabel lblLocation;
  private javax.swing.JTextField lblTime;
  // End of variables declaration//GEN-END:variables
}
