/**/
SELECT 
  "ALLOC_TEACHER"."PERSON" AS "TeacherId", 
  "ALLOC_HELPER"."JOB" AS "HelperJob", 
  "ALLOC_HELPER"."PERSON" AS "HelperId", 
  "ALLOC_TEACHER"."JOB" AS "TeacherJob", 
  "CONTEST"."DESCRIPTION" AS "ContestTitle", 
  "PERSON_TEACHER"."SURNAME" AS "TeacherSurname", 
  "PERSON_TEACHER"."GIVENNAME" AS "TeacherGivenname", 
  "PERSON_HELPER"."SURNAME" AS "HelperSurname", 
  "PERSON_HELPER"."GIVENNAME" AS "HelperGivenname", 
  "PERSON_HELPER"."TELEPHONE", 
  "PERSON_HELPER"."MOBILE", 
  "PERSON_HELPER"."EMAIL", 
  "TIMESLOT"."DAYOFWEEK", 
  "TIMESLOT"."DAYIDX",
  "TIMESLOT"."DATUM", 
  "TIMESLOT"."TIMEOFDAYPRINT", 
  "TIMESLOT"."TIMEOFDAYIDX",
  "LOCATION"."BUILDING" 
/**/
FROM 
  "APP"."ALLOCATION" AS "ALLOC_TEACHER"
   LEFT JOIN "APP"."ALLOCATION" AS "ALLOC_HELPER"
   ON "ALLOC_HELPER"."EVENT" = "ALLOC_TEACHER"."EVENT" 
   LEFT JOIN "APP"."PERSON" AS "PERSON_TEACHER"
   ON "ALLOC_TEACHER"."PERSON" = "PERSON_TEACHER"."PERSONID" 
   LEFT JOIN "APP"."PERSON" AS "PERSON_HELPER"
   ON "ALLOC_HELPER"."PERSON" = "PERSON_HELPER"."PERSONID" 
   LEFT JOIN   "APP"."EVENT" AS "EVENT"
   ON "ALLOC_TEACHER"."EVENT" = "EVENT"."EVENTID"
   LEFT JOIN "APP"."TIMESLOT" AS "TIMESLOT"
   ON "EVENT"."TIMESLOT" = "TIMESLOT"."TIMESLOTID" 
   LEFT JOIN  "APP"."CONTEST" AS "CONTEST"
   ON  "EVENT"."CONTEST" = "CONTEST"."CONTESTID"
   LEFT JOIN  "APP"."LOCATION" AS "LOCATION"
   ON  "EVENT"."LOCATION" = "LOCATION"."LOCATIONID"
/**/
WHERE
  "ALLOC_TEACHER"."JOB" = 'LEHRER'
  AND  "ALLOC_HELPER"."JOB" <> 'LEHRER'
/**/
ORDER BY 
  "TeacherId" ASC, 
  "EVENT"."TIMESLOT" ASC, 
  "HelperJob" ASC
