SELECT 
  "ALLOC_TEACHER"."PERSON" AS "TeacherId", 
  "EVENT"."TIMESLOT", 
  "ALLOC_HELPER"."JOB" AS "HelperJob", 

  "ALLOC_HELPER"."PERSON" AS "HelperId", 
  "ALLOC_TEACHER"."JOB" AS "TeacherJob", 
  "CONTEST"."DESCRIPTION" AS "ContestTitle", 
  "PERSON_TEACHER"."SURNAME" AS "TeacherSurname", 
  "PERSON_TEACHER"."GIVENNAME" AS "TeacherGivenname", 
  "PERSON_HELPER"."SURNAME" AS "HelperSurname", 
  "PERSON_HELPER"."GIVENNAME" AS "HelperGivenname", 
  "PERSON_HELPER"."TELEPHONE", 
  "PERSON_HELPER"."MOBILE", 
  "PERSON_HELPER"."EMAIL", 
  "TIMESLOT"."DAYOFWEEK", 
  "TIMESLOT"."DATUM", 
  "TIMESLOT"."TIMEOFDAYPRINT", 
  "LOCATION"."BUILDING" 
FROM 
  "APP"."ALLOCATION" AS "ALLOC_TEACHER", 
  "APP"."ALLOCATION" AS "ALLOC_HELPER", 
  "APP"."PERSON" AS "PERSON_TEACHER", 
  "APP"."PERSON" AS "PERSON_HELPER",
  "APP"."EVENT" AS "EVENT",
  "APP"."TIMESLOT" AS "TIMESLOT",
  "APP"."CONTEST" AS "CONTEST",
  "APP"."LOCATION" AS "LOCATION"
WHERE 
  "ALLOC_HELPER"."EVENT" = "ALLOC_TEACHER"."EVENT" 
AND 
  "ALLOC_HELPER"."PERSON" = "PERSON_HELPER"."PERSONID" 
AND 
  "ALLOC_TEACHER"."PERSON" = "PERSON_TEACHER"."PERSONID" 
AND 
  "ALLOC_TEACHER"."PERSON" = "PERSON_TEACHER"."PERSONID" 
AND 
  "ALLOC_HELPER"."PERSON" = "PERSON_HELPER"."PERSONID" 
AND 
  "ALLOC_TEACHER"."EVENT" = "EVENT"."EVENTID"
AND 
  "EVENT"."TIMESLOT" = "TIMESLOT"."TIMESLOTID" 
AND 
  "EVENT"."CONTEST" = "CONTEST"."CONTESTID"
AND 
  "EVENT"."LOCATION" = "LOCATION"."LOCATIONID"
AND 
  "ALLOC_TEACHER"."JOB" = 'LEHRER' 
AND 
  "ALLOC_HELPER"."JOB" <> 'LEHRER'
ORDER BY 
  "TeacherId" ASC, 
  "EVENT"."TIMESLOT" ASC, 
  "HelperJob" ASC
