/*
 * Copyright 2013 Harald Postner<harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.location;

import de.free_creations.nbPhonAPI.Manager;
import org.junit.Test;

/**
 *
 * @author Harald Postner<harald at free-creations.de>
 */
public class TimeTableContestComboBoxVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form TimeTableContestVisualTest
   */
  public TimeTableContestComboBoxVisualTest() {
    boolean open = Manager.assertOpen();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    timeTableContestComboBox1 = new de.free_creations.editors.location.TimeTableContestComboBox();
    lblItem = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    btnSetItemTo6 = new javax.swing.JButton();
    btnSetItemToNull = new javax.swing.JButton();
    btnSetItemTo10000 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    timeTableContestComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        timeTableContestComboBox1ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(lblItem, org.openide.util.NbBundle.getMessage(TimeTableContestComboBoxVisualTest.class, "TimeTableContestComboBoxVisualTest.lblItem.text")); // NOI18N
    lblItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TimeTableContestComboBoxVisualTest.class, "TimeTableContestComboBoxVisualTest.jLabel2.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(btnSetItemTo6, org.openide.util.NbBundle.getMessage(TimeTableContestComboBoxVisualTest.class, "TimeTableContestComboBoxVisualTest.btnSetItemTo6.text")); // NOI18N
    btnSetItemTo6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetItemTo6ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetItemToNull, org.openide.util.NbBundle.getMessage(TimeTableContestComboBoxVisualTest.class, "TimeTableContestComboBoxVisualTest.btnSetItemToNull.text")); // NOI18N
    btnSetItemToNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetItemToNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetItemTo10000, org.openide.util.NbBundle.getMessage(TimeTableContestComboBoxVisualTest.class, "TimeTableContestComboBoxVisualTest.btnSetItemTo10000.text")); // NOI18N
    btnSetItemTo10000.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetItemTo10000ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(btnSetItemTo10000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(btnSetItemToNull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timeTableContestComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel2)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnSetItemTo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap(46, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addComponent(timeTableContestComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(47, 47, 47)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(7, 7, 7)
        .addComponent(btnSetItemToNull)
        .addGap(18, 18, 18)
        .addComponent(btnSetItemTo6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnSetItemTo10000)
        .addContainerGap(56, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void timeTableContestComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTableContestComboBox1ActionPerformed
    // TODO add your handling code here:
    Integer selectedContestId = timeTableContestComboBox1.getSelectedContestId();
    lblItem.setText(String.format("%s", selectedContestId));
  }//GEN-LAST:event_timeTableContestComboBox1ActionPerformed

  private void btnSetItemToNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetItemToNullActionPerformed
    // TODO add your handling code here:
    timeTableContestComboBox1.setSelectedContestId(null);
  }//GEN-LAST:event_btnSetItemToNullActionPerformed

  private void btnSetItemTo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetItemTo6ActionPerformed
    // TODO add your handling code here:
    timeTableContestComboBox1.setSelectedContestId(6);
  }//GEN-LAST:event_btnSetItemTo6ActionPerformed

  private void btnSetItemTo10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetItemTo10000ActionPerformed
    // TODO add your handling code here:
    timeTableContestComboBox1.setSelectedContestId(10000);
  }//GEN-LAST:event_btnSetItemTo10000ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TimeTableContestComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TimeTableContestComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TimeTableContestComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TimeTableContestComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TimeTableContestComboBoxVisualTest().setVisible(true);
      }
    });
  }

  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSetItemTo10000;
  private javax.swing.JButton btnSetItemTo6;
  private javax.swing.JButton btnSetItemToNull;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lblItem;
  private de.free_creations.editors.location.TimeTableContestComboBox timeTableContestComboBox1;
  // End of variables declaration//GEN-END:variables
}
