/*
 * Copyright 2014 Harald Postner<harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.contest;

import de.free_creations.editors.contest.AllocationTable.CellKey;
import de.free_creations.nbPhonAPI.Manager;
import org.junit.Test;

/**
 *
 * @author Harald Postner<harald at free-creations.de>
 */
public class AllocationTableCellPanelVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form AllocationTableCellPanelVisualTest
   */
  public AllocationTableCellPanelVisualTest() {
    boolean open = Manager.assertOpen();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    allocationTableCellPanel1 = new de.free_creations.editors.contest.AllocationTableCellPanel();
    btnSetCellKeyNull = new javax.swing.JButton();
    btnSetCellKeyNullNull = new javax.swing.JButton();
    btnSetCellKey_1_1 = new javax.swing.JButton();
    btnSelected = new javax.swing.JToggleButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));

    org.openide.awt.Mnemonics.setLocalizedText(allocationTableCellPanel1, org.openide.util.NbBundle.getMessage(AllocationTableCellPanelVisualTest.class, "AllocationTableCellPanelVisualTest.allocationTableCellPanel1.text")); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(allocationTableCellPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(allocationTableCellPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
    );

    org.openide.awt.Mnemonics.setLocalizedText(btnSetCellKeyNull, org.openide.util.NbBundle.getMessage(AllocationTableCellPanelVisualTest.class, "AllocationTableCellPanelVisualTest.btnSetCellKeyNull.text")); // NOI18N
    btnSetCellKeyNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetCellKeyNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetCellKeyNullNull, org.openide.util.NbBundle.getMessage(AllocationTableCellPanelVisualTest.class, "AllocationTableCellPanelVisualTest.btnSetCellKeyNullNull.text")); // NOI18N
    btnSetCellKeyNullNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetCellKeyNullNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetCellKey_1_1, org.openide.util.NbBundle.getMessage(AllocationTableCellPanelVisualTest.class, "AllocationTableCellPanelVisualTest.btnSetCellKey_1_1.text")); // NOI18N
    btnSetCellKey_1_1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetCellKey_1_1ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSelected, org.openide.util.NbBundle.getMessage(AllocationTableCellPanelVisualTest.class, "AllocationTableCellPanelVisualTest.btnSelected.text")); // NOI18N
    btnSelected.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSelectedActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetCellKeyNull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetCellKey_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetCellKeyNullNull, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetCellKeyNull)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetCellKeyNullNull)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetCellKey_1_1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSelected)
        .addGap(14, 14, 14))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedActionPerformed
    // TODO add your handling code here:
    allocationTableCellPanel1.setSelected(btnSelected.isSelected());
  }//GEN-LAST:event_btnSelectedActionPerformed

  private void btnSetCellKeyNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCellKeyNullActionPerformed
    // TODO add your handling code here:
    allocationTableCellPanel1.setKey(null);
  }//GEN-LAST:event_btnSetCellKeyNullActionPerformed

  private void btnSetCellKeyNullNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCellKeyNullNullActionPerformed
    // TODO add your handling code here:
    allocationTableCellPanel1.setKey(new CellKey(null, null));
  }//GEN-LAST:event_btnSetCellKeyNullNullActionPerformed

  private void btnSetCellKey_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCellKey_1_1ActionPerformed
    allocationTableCellPanel1.setKey(new CellKey(1, "LEHRER"));
  }//GEN-LAST:event_btnSetCellKey_1_1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AllocationTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AllocationTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AllocationTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AllocationTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new AllocationTableCellPanelVisualTest().setVisible(true);
      }
    });
  }

  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private de.free_creations.editors.contest.AllocationTableCellPanel allocationTableCellPanel1;
  private javax.swing.JToggleButton btnSelected;
  private javax.swing.JButton btnSetCellKeyNull;
  private javax.swing.JButton btnSetCellKeyNullNull;
  private javax.swing.JButton btnSetCellKey_1_1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
