/*
 * Copyright 2013 Harald Postner<harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.contest;

import de.free_creations.dbEntities.Event;
import de.free_creations.dbEntities.Location;
import de.free_creations.nbPhonAPI.DataBaseNotReadyException;
import de.free_creations.nbPhonAPI.Manager;
import org.junit.Test;
import org.openide.util.Exceptions;

/**
 *
 * @author Harald Postner<harald at free-creations.de>
 */
public class TimeTableCellPanelVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form TimeTableCellPanelVisiualTest
   */
  public TimeTableCellPanelVisualTest() {
    boolean open = Manager.assertOpen();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    borderPanel = new javax.swing.JPanel();
    timeTableCellPanel1 = new de.free_creations.editors.contest.TimeTableCellPanel();
    btnSetNull = new javax.swing.JButton();
    btnSetEvent_5 = new javax.swing.JButton();
    btnSelected = new javax.swing.JToggleButton();
    btnSetEvent45 = new javax.swing.JButton();
    btnSetEventMinusOne = new javax.swing.JButton();
    btnChangeLocation = new javax.swing.JButton();
    btnChangeEvent = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    borderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    javax.swing.GroupLayout borderPanelLayout = new javax.swing.GroupLayout(borderPanel);
    borderPanel.setLayout(borderPanelLayout);
    borderPanelLayout.setHorizontalGroup(
      borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderPanelLayout.createSequentialGroup()
        .addComponent(timeTableCellPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );
    borderPanelLayout.setVerticalGroup(
      borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(borderPanelLayout.createSequentialGroup()
        .addComponent(timeTableCellPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );

    org.openide.awt.Mnemonics.setLocalizedText(btnSetNull, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnSetNull.text")); // NOI18N
    btnSetNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetEvent_5, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnSetEvent_5.text")); // NOI18N
    btnSetEvent_5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetEvent_5ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSelected, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnSelected.text")); // NOI18N
    btnSelected.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSelectedActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetEvent45, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnSetEvent45.text")); // NOI18N
    btnSetEvent45.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetEvent45ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetEventMinusOne, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnSetEventMinusOne.text")); // NOI18N
    btnSetEventMinusOne.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetEventMinusOneActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnChangeLocation, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnChangeLocation.text")); // NOI18N
    btnChangeLocation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChangeLocationActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnChangeEvent, org.openide.util.NbBundle.getMessage(TimeTableCellPanelVisualTest.class, "TimeTableCellPanelVisualTest.btnChangeEvent.text")); // NOI18N
    btnChangeEvent.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChangeEventActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(borderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetNull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetEvent_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetEvent45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetEventMinusOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnChangeLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnChangeEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(borderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(12, 12, 12)
        .addComponent(btnSetNull)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetEvent_5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetEvent45)
        .addGap(7, 7, 7)
        .addComponent(btnSetEventMinusOne)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSelected)
        .addGap(19, 19, 19)
        .addComponent(btnChangeEvent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnChangeLocation)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedActionPerformed

    timeTableCellPanel1.setSelected(btnSelected.isSelected());
  }//GEN-LAST:event_btnSelectedActionPerformed

  private void btnSetEvent_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetEvent_5ActionPerformed

    timeTableCellPanel1.setValue(5);
  }//GEN-LAST:event_btnSetEvent_5ActionPerformed

  private void btnSetNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNullActionPerformed
    // TODO add your handling code here:
    timeTableCellPanel1.setValue(null);
  }//GEN-LAST:event_btnSetNullActionPerformed

  private void btnSetEvent45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetEvent45ActionPerformed

    timeTableCellPanel1.setValue(45);
  }//GEN-LAST:event_btnSetEvent45ActionPerformed

  private void btnSetEventMinusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetEventMinusOneActionPerformed

    timeTableCellPanel1.setValue(-1);
  }//GEN-LAST:event_btnSetEventMinusOneActionPerformed

  private void btnChangeEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeEventActionPerformed

    Integer eventId = timeTableCellPanel1.getEventId();
    if (eventId != null) {
      try {
        Event e = Manager.getEventCollection().findEntity(eventId);
        if (e != null) {
          e.setScheduled(!e.isScheduled());
        }
      } catch (DataBaseNotReadyException ex) {
        Exceptions.printStackTrace(ex);
      }
    }
  }//GEN-LAST:event_btnChangeEventActionPerformed

  private void btnChangeLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeLocationActionPerformed
    // TODO add your handling code here:
    Integer locationId = timeTableCellPanel1.getLocationId();
    if (locationId != null) {
      try {
        Location l = Manager.getLocationCollection().findEntity(locationId);
        l.setName(l.getName()+" Test");
      } catch (DataBaseNotReadyException ex) {
        Exceptions.printStackTrace(ex);
      }
    }
  }//GEN-LAST:event_btnChangeLocationActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TimeTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TimeTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TimeTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TimeTableCellPanelVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TimeTableCellPanelVisualTest().setVisible(true);
      }
    });
  }

  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel borderPanel;
  private javax.swing.JButton btnChangeEvent;
  private javax.swing.JButton btnChangeLocation;
  private javax.swing.JToggleButton btnSelected;
  private javax.swing.JButton btnSetEvent45;
  private javax.swing.JButton btnSetEventMinusOne;
  private javax.swing.JButton btnSetEvent_5;
  private javax.swing.JButton btnSetNull;
  private de.free_creations.editors.contest.TimeTableCellPanel timeTableCellPanel1;
  // End of variables declaration//GEN-END:variables
}
