/*
 * Copyright 2013 Harald Postner <Harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.person;

import de.free_creations.dbEntities.Job;
import de.free_creations.nbPhonAPI.Manager;

import org.junit.Ignore;
import org.junit.Test;

/**
 *
 * @author Harald Postner <Harald at free-creations.de>
 */
public class ContestTypeComboBoxVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form TimeTableVisualTest
   */
  public ContestTypeComboBoxVisualTest() {
    
  }

  protected void initialize() {
    initComponents();
    if(Manager.isOpen()){
      jLabel1.setText("Connection to DB OK.");
    }else{
       jLabel1.setText("DB not connected!!!");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnSetNull = new javax.swing.JButton();
    btnSetEnsemble = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    contestTypeComboBox1 = new de.free_creations.editors.person.ContestTypeComboBox();
    edSelectedItem = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    org.openide.awt.Mnemonics.setLocalizedText(btnSetNull, org.openide.util.NbBundle.getMessage(ContestTypeComboBoxVisualTest.class, "ContestTypeComboBoxVisualTest.btnSetNull.text")); // NOI18N
    btnSetNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetEnsemble, org.openide.util.NbBundle.getMessage(ContestTypeComboBoxVisualTest.class, "ContestTypeComboBoxVisualTest.btnSetEnsemble.text")); // NOI18N
    btnSetEnsemble.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetEnsembleActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ContestTypeComboBoxVisualTest.class, "ContestTypeComboBoxVisualTest.jLabel1.text")); // NOI18N

    contestTypeComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        contestTypeComboBox1ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(edSelectedItem, org.openide.util.NbBundle.getMessage(ContestTypeComboBoxVisualTest.class, "ContestTypeComboBoxVisualTest.edSelectedItem.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(139, 139, 139)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
          .addComponent(btnSetNull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnSetEnsemble, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
          .addComponent(contestTypeComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(edSelectedItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(166, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(contestTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(btnSetNull)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnSetEnsemble)
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(edSelectedItem)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSetNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetNullActionPerformed
    // TODO add your handling code here:
    contestTypeComboBox1.setSelectedContestTypeId(null);

  }//GEN-LAST:event_btnSetNullActionPerformed

  private void btnSetEnsembleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetEnsembleActionPerformed
    // TODO add your handling code here:
    contestTypeComboBox1.setSelectedContestTypeId("ENSEMBLE");

  }//GEN-LAST:event_btnSetEnsembleActionPerformed

  private void contestTypeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contestTypeComboBox1ActionPerformed
    // TODO add your handling code here:
    edSelectedItem.setText(String.format("%s", contestTypeComboBox1.getSelectedContestTypeId()));
  }//GEN-LAST:event_contestTypeComboBox1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ContestTypeComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ContestTypeComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ContestTypeComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ContestTypeComboBoxVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        ContestTypeComboBoxVisualTest funktionenComboBoxVisualTest = new ContestTypeComboBoxVisualTest();
        funktionenComboBoxVisualTest.initialize();
        funktionenComboBoxVisualTest.setVisible(true);
      }
    });
  }
  
  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSetEnsemble;
  private javax.swing.JButton btnSetNull;
  private de.free_creations.editors.person.ContestTypeComboBox contestTypeComboBox1;
  private javax.swing.JLabel edSelectedItem;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
