/*
 * Copyright 2013 Harald Postner <Harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.editors.person;

import de.free_creations.nbPhonAPI.DataBaseNotReadyException;
import de.free_creations.nbPhonAPI.Manager;
import de.free_creations.nbPhonAPI.TimeSlotCollection;
import org.junit.Test;
import org.openide.util.Exceptions;

/**
 *
 * @author Harald Postner <Harald at free-creations.de>
 */
public class TimeTableVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form TimeTableVisualTest
   */
  public TimeTableVisualTest() {
  }

  protected void initialize() {
    boolean open = Manager.assertOpen();
    if(open){
      try {
        Manager.commit();
        TimeSlotCollection.addTestItem();
      } catch (DataBaseNotReadyException ex) {
        Exceptions.printStackTrace(ex);
      }
      
    }
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    timeTableAbove = new de.free_creations.editors.person.TimeTable();
    btnSetPersonTo56 = new javax.swing.JButton();
    setPersonToNull = new javax.swing.JButton();
    btnSetPersonTo56Below = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    timeTableBelow = new de.free_creations.editors.person.TimeTable();
    setPersonToNullBelow = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jScrollPane2.setViewportView(timeTableAbove);

    org.openide.awt.Mnemonics.setLocalizedText(btnSetPersonTo56, org.openide.util.NbBundle.getMessage(TimeTableVisualTest.class, "TimeTableVisualTest.btnSetPersonTo56.text")); // NOI18N
    btnSetPersonTo56.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetPersonTo56ActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(setPersonToNull, org.openide.util.NbBundle.getMessage(TimeTableVisualTest.class, "TimeTableVisualTest.setPersonToNull.text")); // NOI18N
    setPersonToNull.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        setPersonToNullActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(btnSetPersonTo56Below, org.openide.util.NbBundle.getMessage(TimeTableVisualTest.class, "TimeTableVisualTest.btnSetPersonTo56Below.text")); // NOI18N
    btnSetPersonTo56Below.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSetPersonTo56BelowActionPerformed(evt);
      }
    });

    jScrollPane3.setViewportView(timeTableBelow);

    org.openide.awt.Mnemonics.setLocalizedText(setPersonToNullBelow, org.openide.util.NbBundle.getMessage(TimeTableVisualTest.class, "TimeTableVisualTest.setPersonToNullBelow.text")); // NOI18N
    setPersonToNullBelow.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        setPersonToNullBelowActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
      .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnSetPersonTo56)
              .addComponent(setPersonToNull, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(btnSetPersonTo56Below)
          .addComponent(setPersonToNullBelow, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetPersonTo56)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(setPersonToNull)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSetPersonTo56Below)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(setPersonToNullBelow)
        .addContainerGap(34, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSetPersonTo56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetPersonTo56ActionPerformed
    // TODO add your handling code here:
    timeTableAbove.setPersonId(56);
  }//GEN-LAST:event_btnSetPersonTo56ActionPerformed

  private void setPersonToNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPersonToNullActionPerformed
    // TODO add your handling code here:
    timeTableAbove.setPersonId(null);
  }//GEN-LAST:event_setPersonToNullActionPerformed

  private void btnSetPersonTo56BelowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetPersonTo56BelowActionPerformed
    // TODO add your handling code here:
    timeTableBelow.setPersonId(56);
  }//GEN-LAST:event_btnSetPersonTo56BelowActionPerformed

  private void setPersonToNullBelowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPersonToNullBelowActionPerformed
    // TODO add your handling code here:
    timeTableBelow.setPersonId(null);
  }//GEN-LAST:event_setPersonToNullBelowActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TimeTableVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TimeTableVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TimeTableVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TimeTableVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        TimeTableVisualTest timeTableVisualTest = new TimeTableVisualTest();
        timeTableVisualTest.initialize();
        timeTableVisualTest.setVisible(true);
      }
    });
  }

  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSetPersonTo56;
  private javax.swing.JButton btnSetPersonTo56Below;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JButton setPersonToNull;
  private javax.swing.JButton setPersonToNullBelow;
  private de.free_creations.editors.person.TimeTable timeTableAbove;
  private de.free_creations.editors.person.TimeTable timeTableBelow;
  // End of variables declaration//GEN-END:variables
}
