/*
 * Copyright 2013 Harald Postner <Harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.free_creations.nbPhon4Netbeans;

import java.awt.Image;
import javax.swing.Icon;
import org.junit.Test;
import static de.free_creations.nbPhon4Netbeans.IconManager.*;
import java.awt.image.BufferedImage;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Harald Postner <Harald at free-creations.de>
 */
public class IconsVisualTest extends javax.swing.JFrame {

  /**
   * Creates new form IconsVisualTest
   */
  public IconsVisualTest() {
    initComponents();
    ImageIcon[] items = {
      iconManager().image2icon(iconManager().iconLocation),
      iconManager().image2icon(iconManager().iconContest),
      iconManager().image2icon(iconManager().iconChildFemale),
      iconManager().image2icon(iconManager().iconChildMale),
      iconManager().image2icon(iconManager().iconTeacher),
      iconManager().image2icon(iconManager().iconMan),
      iconManager().image2icon(iconManager().iconWoman),
      iconManager().image2icon(iconManager().iconStar),
      iconManager().image2icon(iconManager().iconNobody),
      iconManager().image2icon(iconManager().iconGroupleader)};
    DefaultComboBoxModel<ImageIcon> model = new DefaultComboBoxModel<>(items);
    cbIcons.setModel(model);


  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnabled = new javax.swing.JLabel();
        cbInstrument = new javax.swing.JComboBox();
        cbIcons = new javax.swing.JComboBox();
        lblDisabled = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(lblEnabled, org.openide.util.NbBundle.getMessage(IconsVisualTest.class, "IconsVisualTest.lblEnabled.text")); // NOI18N

        cbInstrument.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLOCKFLOETE", "GITARRE", "HORN", "KLARINETTE", "KLAVIER-DUO", "KLAVIER-STREICH", "KUNSTLIED", "MUSICAL", "OBOE", "ORGEL", "POP", "POSAUNE", "QUERFLOETE", "SAX", "SEL-BESETZ", "TROMPETE", "TUBA", " " }));
        cbInstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInstrumentActionPerformed(evt);
            }
        });

        cbIcons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIcons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIconsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblDisabled, org.openide.util.NbBundle.getMessage(IconsVisualTest.class, "IconsVisualTest.lblDisabled.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbInstrument, 0, 206, Short.MAX_VALUE)
                        .addComponent(cbIcons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisabled, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisabled, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(cbIcons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cbInstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void cbInstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInstrumentActionPerformed

    setIcon();
  }//GEN-LAST:event_cbInstrumentActionPerformed

  private void cbIconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIconsActionPerformed
    // 
    setIcon();
  }//GEN-LAST:event_cbIconsActionPerformed

  private void setIcon() {

    Object selectedItem = cbInstrument.getSelectedItem();
    String category = (selectedItem instanceof String) ? (String) selectedItem : null;
    Object selectedItem2 = cbIcons.getSelectedItem();
    Image baseImage = (selectedItem2 instanceof ImageIcon) ? ((ImageIcon) selectedItem2).getImage() : null;

    BufferedImage bbaseImage = (BufferedImage) baseImage;


    BufferedImage instrumentedImage = iconManager().getInstrumentedImage(bbaseImage, category);
    BufferedImage disabledImage = iconManager().getDisabledImage(instrumentedImage);
    Icon enabledIcon = iconManager().image2icon(instrumentedImage);
    Icon disabledIcon = iconManager().image2icon(disabledImage);

    lblEnabled.setIcon(enabledIcon);
    lblDisabled.setIcon(disabledIcon);

  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(IconsVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(IconsVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(IconsVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(IconsVisualTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new IconsVisualTest().setVisible(true);
      }
    });
  }

  @Test
  public void showIt() {
    System.out.println("Use \"Run File\" to see this test.");
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbIcons;
    private javax.swing.JComboBox cbInstrument;
    private javax.swing.JLabel lblDisabled;
    private javax.swing.JLabel lblEnabled;
    // End of variables declaration//GEN-END:variables
}
