/*
 * Copyright 2013 Harald Postner<harald at free-creations.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------
--                      D r o p (o l d)    T a b l e s
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

ALTER TABLE "APP"."AVAILABILITY" DROP CONSTRAINT "AVAILABILITY_FK1";
ALTER TABLE "APP"."AVAILABILITY" DROP CONSTRAINT "AVAILABILITY_FK2";
ALTER TABLE "APP"."PERSON" DROP CONSTRAINT PERSON_FK1;
ALTER TABLE "APP"."PERSON" DROP CONSTRAINT PERSON_FK2;
ALTER TABLE "APP"."CONTEST" DROP CONSTRAINT CONTEST_FK;
ALTER TABLE "APP"."ALLOCATION" DROP CONSTRAINT ALLOCATION_FK1;
ALTER TABLE "APP"."ALLOCATION" DROP CONSTRAINT ALLOCATION_FK2;
ALTER TABLE "APP"."ALLOCATION" DROP CONSTRAINT ALLOCATION_FK3;
ALTER TABLE "APP"."ALLOCATION" DROP CONSTRAINT ALLOCATION_FK4;

DROP TABLE "APP"."PERSON";
DROP TABLE "APP"."CONTEST";
DROP TABLE "APP"."AVAILABILITY";
DROP TABLE "APP"."ALLOCATION";
DROP TABLE "APP"."JOB";
DROP TABLE "APP"."TIMESLOT";
DROP TABLE "APP"."TEAM";

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------
--                      C r e a t e    T a b l e s
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- Table TIMESLOT
-- Describes the basic calendar.
-- Each record describes an elementary block of time.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."TIMESLOT" (
  "ZEITID" INTEGER NOT NULL, 
  "TAG" INTEGER, 
  "TAGESZEIT" INTEGER, 
  "DATUM" DATE, 
  "STARTZEIT" TIME, 
  "ENDEZEIT" TIME, 
  "WOCHENTAG" VARCHAR(50), 
  "LABEL" VARCHAR(50), 
  "TAGESZEITPRINT" VARCHAR(50)
);

-- -----------------------------------------------------------------------------
-- Table PERSON
-- Describes all persons by their addresses and their preferences.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."PERSON" (
  "PERSONID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "FAMILIENNAME" VARCHAR(50), 
  "VORNAME" VARCHAR(50), 
  "HERRFRAU" VARCHAR(50), 
  "PLZ" VARCHAR(50), 
  "ORT" VARCHAR(50), 
  "STRASSE" VARCHAR(50), 
  "TELNR" VARCHAR(50), 
  "HANDY" VARCHAR(50), 
  "EMAIL" VARCHAR(50), 
  "ALTERSGRUPPE" VARCHAR(50), 
  "NOTIZ" VARCHAR(255), 
  "GEWUENSCHTEWERTUNG" VARCHAR(50), 
  "GEWUENSCHTEFUNKTION" VARCHAR(50), 
  "GEWUENSCHTERKOLLEGE" INTEGER,  
  "TEAM" INTEGER, 
  "LETZTEAENDERUNG" TIMESTAMP
);
-- -----------------------------------------------------------------------------
-- Table CONTEST
-- Describes the details of the contests.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."CONTEST" (
  "CONTESTID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "NAME" VARCHAR(50), 
  "WERTUNGSTYP" VARCHAR(50), 
  "VERANTWORTLICH" INTEGER, 
  "WERTUNG" VARCHAR(50), 
  "WERTUNGSRAUM" VARCHAR(50), 
  "AUSTRAGGUNGSORTPLANNR" VARCHAR(50), 
  "AUSTRAGGUNGSORT" VARCHAR(50), 
  "ZEITFREITAG" VARCHAR(50), 
  "ZEITSAMSTAG" VARCHAR(50), 
  "ZEITSONNTAG" VARCHAR(50)
);

-- -----------------------------------------------------------------------------
-- Table AVAILABILITY
-- Each record describes the availability of a given person for a specific
-- time slot. When a new person record is created, for each timeslot a corresponding
-- availability record mmust be inserted.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."AVAILABILITY" (
  "VERFUEGID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "PERSONID" INTEGER NOT NULL, 
  "ZEITID" INTEGER NOT NULL, 
  "VERFUEGBAR" INTEGER, 
  "LETZTEAENDERUNG" TIMESTAMP
);
-- -----------------------------------------------------------------------------
-- Table ALLOCATION
-- Each record of this table allocates a given person for a time slot 
-- to a task (identified by the function).
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."ALLOCATION" (
  "ALLOCATIONID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ZEITID" INTEGER NOT NULL, 
  "CONTESTID" INTEGER NOT NULL, 
  "FUNKTIONID" VARCHAR(50) NOT NULL, 
  "PERSONID" INTEGER NOT NULL, 
  "LETZTEAENDERUNG" TIMESTAMP, 
  "PLANER" VARCHAR(50), 
  "ERKLAERUNG" VARCHAR(32000)
);

-- -----------------------------------------------------------------------------
-- Table JOB
-- Describes in detail the task of a person.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."JOB" (
  "FUNKTIONID" VARCHAR(50) NOT NULL, 
  "FUNKTIONNAME" VARCHAR(50), 
  "SORTVALUE" INTEGER
);
-- -----------------------------------------------------------------------------
-- Table G R O U P
-- The participants might be joined into teams.
-- -----------------------------------------------------------------------------
CREATE TABLE "APP"."TEAM" (
  "TEAM" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "NAME" VARCHAR(50)
);
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------
--                      P r i m a r y    K e y s
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------
ALTER TABLE "APP"."JOB" 
  ADD CONSTRAINT "FunctionPrimKey" PRIMARY KEY ("FUNKTIONID");
ALTER TABLE "APP"."CONTEST" 
  ADD CONSTRAINT "ContestPrimKey" PRIMARY KEY ("CONTESTID");
ALTER TABLE "APP"."ALLOCATION" 
  ADD CONSTRAINT "AllocationPrimKey" PRIMARY KEY ("ALLOCATIONID");
ALTER TABLE "APP"."TIMESLOT" 
  ADD CONSTRAINT "TimeslotPrimKey" PRIMARY KEY ("ZEITID");
ALTER TABLE "APP"."AVAILABILITY" 
  ADD CONSTRAINT "AvailabilityPrimKey" PRIMARY KEY ("VERFUEGID");
ALTER TABLE "APP"."PERSON" 
  ADD CONSTRAINT "PersonPrimKey" PRIMARY KEY ("PERSONID");
ALTER TABLE "APP"."TEAM" 
  ADD CONSTRAINT "TeamPrimKey" PRIMARY KEY ("TEAM");

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------
--                      F o r e i g n    K e y s
-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- Table CONTEST
ALTER TABLE "APP"."CONTEST" 
  ADD CONSTRAINT "CONTEST_FK" FOREIGN KEY ("VERANTWORTLICH") 
  REFERENCES "APP"."PERSON" ("PERSONID") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Table ALLOCATION
ALTER TABLE "APP"."ALLOCATION" 
  ADD CONSTRAINT "ALLOCATION_FK1" FOREIGN KEY ("ZEITID") 
  REFERENCES "APP"."TIMESLOT" ("ZEITID") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."ALLOCATION" 
  ADD CONSTRAINT "ALLOCATION_FK2" FOREIGN KEY ("PERSONID") 
  REFERENCES "APP"."PERSON" ("PERSONID") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."ALLOCATION" 
  ADD CONSTRAINT "ALLOCATION_FK3" FOREIGN KEY ("CONTESTID") 
  REFERENCES "APP"."CONTEST" ("CONTESTID") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."ALLOCATION" 
  ADD CONSTRAINT "ALLOCATION_FK4" FOREIGN KEY ("FUNKTIONID") 
  REFERENCES "APP"."JOB" ("FUNKTIONID") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Table PERSON
ALTER TABLE "APP"."PERSON" 
  ADD CONSTRAINT "PERSON_FK1" FOREIGN KEY ("GEWUENSCHTEFUNKTION") 
  REFERENCES "APP"."JOB" ("FUNKTIONID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."PERSON" 
  ADD CONSTRAINT "PERSON_FK2" FOREIGN KEY ("TEAM") 
  REFERENCES "APP"."TEAM" ("TEAM") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Table AVAILABILITY
ALTER TABLE "APP"."AVAILABILITY"  
  ADD CONSTRAINT "AVAILABILITY_FK1" FOREIGN KEY ("PERSONID") 
  REFERENCES "APP"."PERSON" ("PERSONID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."AVAILABILITY"  
  ADD CONSTRAINT "AVAILABILITY_FK2" FOREIGN KEY ("ZEITID") 
  REFERENCES "APP"."TIMESLOT" ("ZEITID") ON DELETE NO ACTION ON UPDATE NO ACTION;